Add BACE integration
blockbax/integration-templates pull request #9
Opened 2023-10-31 09:35 UTC by arianmaghsoudnia

2023-10-31 09:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/blockbax/integration-templates?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/blockbax/integration-templates?pullRequest=9) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/blockbax/integration-templates?pullRequest=9) it.</sub>

2023-11-01 08:25 UTC, royyeah reviewed
@arianmaghsoudnia I add some comments from my side, I think @arjanvanijzendoorn can best decide who can review the rest

2023-11-01 08:25 UTC, royyeah commented on groups/bace-iot-platform/measurements/config.yml
> +name: Measurements
I would suggest to change the folder to `measurements-webhook` and the name to 'Measurements webhook'

2023-11-01 08:25 UTC, royyeah commented on groups/bace-iot-platform/index.yml
> +name: BACE IoT platform
Because it is a product title I would write 'BACE IoT Platform' with the last word capitalized as well.

2023-11-03 12:25 UTC, arjanvanijzendoorn requested changes
Reviewed 3 commits. 2 comments.

2023-11-03 12:25 UTC, arjanvanijzendoorn commented on groups/bace-iot-platform/measurements-webhook/payloads/testPayload.json
> +[
Can you reformat this file with Visual Studio Code (or something) to fix indentation and make sure there is a newline at the end.

2023-11-03 12:25 UTC, arjanvanijzendoorn commented on groups/bace-iot-platform/measurements-webhook/tests.yml
> +          date: 2023-01-01T00:00:00.000+00:00
Maybe add a test that shows that no measurements are created if required fields are missing?
And a newline at the end of this file 😉

2023-11-20 09:37 UTC, merged